import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fafafa',
  },
  mapContainer: {
    width: '100%',
    height: '100%',
    overflow: 'hidden',
  },
  menuButton: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 1000,
    padding: 10,
    borderRadius: 10,
  },
  menuIcon: {
    fontSize: 40,
    color: '#60BC7C',
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderTopWidth: 7,
    borderColor: '#60BC7C',
    paddingHorizontal: 14,
    paddingTop: 4,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 10,
    boxShadow: '0px -4px 12px rgba(0,0,0,0.15)',
  },
  dragArea: {
    width: '100%',
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dragHandle: {
    width: 55,
    height: 6,
    borderRadius: 10,
    backgroundColor: '#D0D0D0',
  },
  tituloContainer: {
    width: '100%',
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
  },
  titulo: {
    fontSize: 40,
    fontFamily: 'Gurajada',
    color: '#468B5B',
  },
  linhaTitulo: {
    height: 1,
    width: '100%',
    backgroundColor: '#D5D5D5',
  },
  lista: {
    flex: 1,
    width: '100%',
  },
  listaConteudo: {
    paddingHorizontal: 2,
    paddingTop: 10,
    paddingBottom: 25,
  },
  card: {
    backgroundColor: '#D9F5E2',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 9,
    width: '100%',
    minHeight: 105,
  },
  cardLinha: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#B8E8C8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  cardInfo: {
    flex: 1,
    paddingRight: 8,
  },
  nome: {
    fontSize: 20,
    lineHeight: 19,
    fontFamily: 'Gurajada',
    color: '#468B5B',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  rota: {
    fontSize: 15,
    lineHeight: 15,
    fontFamily: 'Gurajada',
    color: '#468B5B',
  },
  informacoes: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    flexWrap: 'wrap',
  },
  info: {
    fontSize: 15,
    lineHeight: 14,
    fontFamily: 'Gurajada',
    color: '#404348',
    marginRight: 14,
  },
  compatibilidade: {
    width: 72,
    minHeight: 70,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: '#A8DDB8',
    paddingLeft: 8,
  },
  compatibilidadeNumero: {
    fontSize: 26,
    lineHeight: 28,
    color: '#468B5B',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  compatibilidadeTexto: {
    fontSize: 11,
    lineHeight: 12,
    fontFamily: 'Gurajada',
    color: '#468B5B',
    marginTop: -2,
    textAlign: 'center',
  },
  botaoVer: {
    marginTop: 3,
    paddingVertical: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  botaoVerTexto: {
    fontSize: 13,
    fontFamily: 'Gurajada',
    color: '#468B5B',
    marginRight: 4,
  },
  detalhesContainer: {
    width: '100%',
    paddingTop: 1,
  },
  divisor: {
    height: 1,
    backgroundColor: '#A8DDB8',
    marginVertical: 8,
  },
  detalhesTitulo: {
    fontSize: 20,
    lineHeight: 19,
    fontFamily: 'Gurajada',
    color: '#468B5B',
    fontWeight: 'bold',
    marginBottom: 6,
  },
  detalhe: {
    fontSize: 15,
    lineHeight: 15,
    fontFamily: 'Gurajada',
    color: '#404348',
    marginBottom: 5,
  },
  botaoEscolher: {
    marginTop: 9,
    backgroundColor: '#468B5B',
    borderRadius: 7,
    paddingVertical: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  botaoEscolherTexto: {
    fontSize: 14,
    fontFamily: 'Gurajada',
    color: '#FFFFFF',
    marginRight: 5,
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 8,
    fontSize: 16,
    fontFamily: 'Gurajada',
    color: '#468B5B',
  },
  vazio: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 25,
  },
  vazioTitulo: {
    fontSize: 22,
    fontFamily: 'Gurajada',
    color: '#333333',
    textAlign: 'center',
  },
  vazioTexto: {
    marginTop: 7,
    fontSize: 15,
    fontFamily: 'Gurajada',
    color: '#777777',
    textAlign: 'center',
  },
});